name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
    push:
        branches: 
            - main

    pull_request: 
        branches:
            - main
jobs:
  pull_request_job:
    #if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the repository
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.x (adjust the version if needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'  # Use the Python version that is compatible with your project

      # Step 3: Install the dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install pytest  # Install pytest
          pip install -r requirements-dev.txt  # If you have a requirements.txt file

      # Step 4: Run the test suite with pytest
      - name: Run tests with pytest
        run: |
          pytest
