name: Run Tests

# Trigger the workflow on every push request
on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Check out the code from the repo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'  # You can specify the version of Python, for example, '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt  

    - name: Run tests
      run: |
        pytest  # Runs the pytest test suite