name: GitHub Actions
run-name: ${{ github.actor }} is running actions
on: 
    push:
        branches: 
            - main

    pull_request: 
        branches:
            - main
jobs:
  pull_request_job:
    # if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: build projen
        run: |
            npx projen build

      # Step 4: Run the test suite with pytest
      - name: Run tests with pytest
        run: |
          pytest
