name: Pull Tests

# Trigger the workflow on every pull request
on:
  pull_request:
    branches:
      - main  # Run tests on pull requests to main
  push:
    branches:
      - main  # Run security scan only on merges to main

jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install pytest pytest-xdist pytest-cov  

    - name: Run tests with coverage report
      run: |
        pytest -n auto --cov=note_api --cov-report=xml  

    - name: Upload coverage file to codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        verbose: true

  snyk-analysis:
    # if: github.ref == 'refs/heads/main' -> if main wasn't specified above
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Specify Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'
    - name: Snyk analysis
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --sarif-file-output=snyk.sarif
        path_to_dependency_file: requirements.txt
        snyk_github_integration_token: ${{ github.token }}
        repository: ${{ github.repository }}
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif
